import { test } from 'node:test'
import assert from 'node:assert/strict'
import { DAYS, DAY_BY_DATE, EXERCISE_BY_ID, MODULES, allDayExercises, dayExercises, dayLabel } from '@/data/curriculum'
import { PLAN_90, PLAN_END, PLAN_START } from '@/data/schedule-90'
import { engagementOf } from '@/lib/curriculum-audit'
import { blockingGate, lockedByGate } from '@/lib/progress'
import { attempt } from '@/lib/test-helpers'
import { parseLocal } from '@/lib/dates'

/**
 * The calendar: the October sprint as it happened (Oct 2–10), then the 90-day
 * ladder plan (Oct 11 → Jan 8) generated by planning/gen.py.
 */

const required = (date: string) => DAY_BY_DATE[date].sections.filter((s) => !s.optional)
const plan = DAYS.filter((d) => d.planDay)
const dateOfRep = new Map(plan.flatMap((d) => dayExercises(d).map((e) => [e.id, d.date] as const)))

// ── the sprint, as it happened ──────────────────────────────────────────────

test('the sprint is recorded as it happened: Oct 2–7 worked, Oct 6 and Oct 8–10 off', () => {
  assert.deepEqual(required('2026-10-02').map((s) => s.id), ['o2-python-recall', 'o2-loops'])
  assert.equal(required('2026-10-03')[0].id, 'o2-enumerate')
  assert.deepEqual(required('2026-10-03').slice(-6).map((s) => s.id), ['o2-dictionaries', 'o2-dict-revision', 'o2-get', 'o2-iter-dicts', 'o2-frequency', 'o2-dict-mastery'])
  for (const id of ['o2-dict-revision', 'o2-dict-mastery']) assert.ok(required('2026-10-03').find((s) => s.id === id)?.gate, `${id} is a mastery check`)
  assert.deepEqual(required('2026-10-04').map((s) => s.id), ['o2-dict-ladder'])
  for (const date of ['2026-10-06', '2026-10-08', '2026-10-09', '2026-10-10']) assert.equal(dayExercises(DAY_BY_DATE[date]).length, 0, `${date} is an off day`)
  assert.equal(dayLabel(DAY_BY_DATE['2026-10-03']), 'October sprint')
})

// ── the 90-day ladder plan ──────────────────────────────────────────────────

test('the plan runs 90 days from Oct 11, and every calendar date has a day', () => {
  assert.equal(PLAN_START, '2026-10-11')
  assert.equal(PLAN_END, '2027-01-08')
  assert.equal(PLAN_90.length, 90)
  assert.equal(plan[0].date, PLAN_START)
  assert.equal(dayLabel(plan[0]), 'Day 1 of 90')
  assert.equal(DAYS[DAYS.length - 1].date, PLAN_END)
  for (let i = 1; i < DAYS.length; i++) assert.equal((parseLocal(DAYS[i].date).getTime() - parseLocal(DAYS[i - 1].date).getTime()) / 86_400_000 | 0, 1, `no gap before ${DAYS[i].date}`)
})

test('rest is protected: nothing on Sundays after day 1, on the days off, and no ladder work in buffer weeks', () => {
  for (const d of plan) {
    const work = dayExercises(d).length + (d.leetcode?.length ?? 0)
    const sunday = parseLocal(d.date).getDay() === 0
    if (sunday && d.date !== PLAN_START) assert.equal(work, 0, `${d.date} is a Sunday`)
    if (['2026-11-26', '2026-11-27', '2026-12-24', '2026-12-25', '2027-01-01'].includes(d.date)) assert.equal(work, 0, `${d.date} is a day off`)
    if (d.phase === 'buffer') for (const s of d.sections.filter((x) => !x.optional)) assert.match(s.id, /^o11-/, `${d.date}: buffer weeks carry interview practice only`)
  }
})

test('the first week is a soft start, and no day asks for more than the ceiling', () => {
  const firstWeek = plan.slice(0, 7)
  for (const d of firstWeek) {
    assert.equal(d.phase, 'soft')
    assert.ok((d.leetcode ?? []).filter((x) => x.type === 'new').length <= 2, d.date)
    assert.ok((d.leetcode ?? []).filter((x) => x.type !== 'new').length <= 2, d.date)
  }
  for (const p of PLAN_90) {
    assert.ok(p.minutes <= 175, `${p.date}: ${p.minutes} real minutes of new work`)
    assert.ok(p.leetcode.filter((x) => x.type !== 'new').length <= 6, `${p.date}: re-solves`)
    assert.ok(p.leetcode.filter((x) => x.type === 'new').length <= 4, `${p.date}: new LeetCode problems`)
  }
})

test('every pattern runs like dictionaries did: ladder, then its mastery check, then its LeetCode problems', () => {
  // [last ladder rep, a rep of the mastery check, first LeetCode problem of the pattern]
  const units: [string, string, number][] = [
    ['cap-two-sum', 'o2-cold-letter-counts', 49],
    ['cap-two-sum-ii', 'd3-cold-reverse', 11],
    ['cap-merge-two-lists', 'd05-cold-search', 141],
    ['cap-invert-tree', 'd06-cold-tree-sum', 572],
    ['cap-course-schedule', 'o8-cold-build', 133],
    ['cap-merge-intervals', 'd9-cold-merge', 57],
    ['cap-house-robber', 'd10-cold-climb', 213],
  ]
  const lcDate = (lc: number) => plan.find((d) => d.leetcode?.some((x) => x.lc === lc && x.type === 'new'))!.date
  for (const [ladder, check, lc] of units) {
    const sec = MODULES.flatMap((m) => m.sections).find((s) => s.exercises.some((e) => e.id === check)) ?? MODULES.flatMap((m) => m.sections).find((s) => s.id === check.split('-cold')[0] + '-cold')!
    const checkRep = sec.exercises[0].id
    assert.ok(dateOfRep.get(ladder)! <= dateOfRep.get(checkRep)!, `${ladder} comes before its check`)
    assert.ok(dateOfRep.get(checkRep)! <= lcDate(lc), `LC ${lc} comes after the check`)
    assert.ok(EXERCISE_BY_ID[checkRep].cleanPass, `${checkRep} only counts when passed without the solution`)
  }
})

test('a mastery check holds everything after it, across days, until it is cleared', () => {
  const gateDay = plan.find((d) => d.sections.some((s) => s.gate))!
  const gate = gateDay.sections.find((s) => s.gate)!
  const later = plan.find((d) => d.date > gateDay.date && dayExercises(d).length > 0 && !d.sections.some((s) => s.gate && s.id === gate.id))!
  const before = DAYS.filter((d) => d.date <= gateDay.date).flatMap((d) => dayExercises(d)).filter((e) => !gate.exercises.some((g) => g.id === e.id))
  const done = before.map((e) => attempt({ exerciseId: e.id }))
  assert.equal(blockingGate(later, 0, done)?.id, gate.id)
  assert.equal(lockedByGate(later, dayExercises(later)[0].id, done)?.id, gate.id)
  // Every part of the check (it can span two days) has to be clean before what follows opens.
  const whole = plan.flatMap((d) => d.sections.filter((s) => s.gate && s.id === gate.id).flatMap((s) => s.exercises))
  const cleared = [...done, ...whole.map((e) => attempt({ exerciseId: e.id }))]
  assert.notEqual(blockingGate(later, 0, cleared)?.id, gate.id)
})

test('a capstone solved in Reps is the first solve; its re-solves happen on LeetCode at widening gaps', () => {
  const capDay = dateOfRep.get('cap-two-sum')!
  const resolves = plan.flatMap((d) => (d.leetcode ?? []).filter((x) => x.lc === 1).map((x) => ({ date: d.date, type: x.type })))
  assert.deepEqual(resolves.map((r) => r.type), ['review1', 'review2', 'review3'])
  assert.ok(resolves[0].date > capDay)
  const gap = (a: string, b: string) => Math.round((parseLocal(b).getTime() - parseLocal(a).getTime()) / 86_400_000)
  assert.ok(gap(capDay, resolves[0].date) >= 3 && gap(capDay, resolves[1].date) >= 10 && gap(capDay, resolves[2].date) >= 30)
  // No LeetCode problem is ever listed as new twice.
  const news = plan.flatMap((d) => (d.leetcode ?? []).filter((x) => x.type === 'new').map((x) => x.lc))
  assert.equal(new Set(news).size, news.length)
})

test('within every section, required reps keep their authored order', () => {
  const order = new Map(MODULES.flatMap((m) => m.sections.flatMap((s) => s.exercises.map((e, i) => [e.id, i] as const))))
  for (const d of DAYS)
    for (const s of d.sections.filter((x) => !x.optional)) {
      const idx = s.exercises.map((e) => order.get(e.id)!)
      assert.deepEqual(idx, [...idx].sort((a, b) => a - b), `${d.date} ${s.id}`)
    }
})

test('nothing is lost: every authored rep is on the calendar exactly once', () => {
  const calendar = DAYS.flatMap((d) => allDayExercises(d).map((e) => e.id))
  const authored = MODULES.flatMap((m) => allDayExercises(m).map((e) => e.id))
  assert.equal(new Set(calendar).size, calendar.length)
  assert.deepEqual([...calendar].sort(), [...authored].sort())
})

test('every capstone is required somewhere on the calendar, except the two the plan leaves out', () => {
  const req = new Set(DAYS.flatMap((d) => dayExercises(d).map((e) => e.id)))
  const LEFT_OUT = ['cap-number-of-provinces'] // Number of Islands teaches the same idea
  for (const m of MODULES) for (const e of allDayExercises(m)) if (e.repType === 'capstone') assert.equal(req.has(e.id), !LEFT_OUT.includes(e.id), e.id)
})

test('ladder days stay code-first (≥ 65% active minutes)', () => {
  for (const d of plan) {
    const ex = dayExercises(d)
    if (ex.length < 4) continue
    const total = ex.reduce((n, e) => n + e.minutes, 0)
    const active = ex.filter((e) => engagementOf(e) === 'active').reduce((n, e) => n + e.minutes, 0)
    assert.ok(active / total >= 0.65, `${d.date}: ${Math.round((100 * active) / total)}% active`)
  }
})

test('the Dictionary ladder is still 30 reps, and the unlabeled set never names its technique', () => {
  const ladder = DAYS.flatMap((d) => d.sections.filter((s) => s.id === 'o2-dict-ladder').flatMap((s) => s.exercises))
  assert.equal(ladder.length, 30)
  const set = MODULES.flatMap((m) => m.sections).find((s) => s.id === 'o11-name-it')!
  for (const e of set.exercises) assert.doesNotMatch(`${e.title} ${e.prompt}`, /\b(set|dict|hash|BFS|DFS|graph|window|binary search|two pointers?|stack|heap|queue)\b/i, e.id)
})
